apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ include "headscale.config" . | indent 4 }}
