apiVersion: v1
kind: Secret
metadata:
  name: headscale-preauth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  preauth-key: {{ .Values.preAuthKey | quote }}
