#!/usr/bin/env python3
"""Regenerate examples/MATRIX.md from real `boxy serve --dryrun` output.

Run from the boxy/ directory:  PYTHONPATH=src python3 hack/gen_matrix.py
Every command in the doc is machine-generated, never hand-written."""

from __future__ import annotations

import contextlib
import io
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
EXAMPLES = ROOT / "src" / "boxy" / "data" / "examples"

# deterministic render: this doc regenerates on arbitrary dev machines, and
# deploy propagates the AMBIENT proxy env into serve commands — scrub it and
# pin the documentation-stable example proxy so the doc still demonstrates
# proxy propagation without baking in anything machine-specific.
for _v in ("http_proxy", "https_proxy", "all_proxy", "no_proxy"):
    os.environ.pop(_v, None)
    os.environ.pop(_v.upper(), None)
os.environ["http_proxy"] = os.environ["https_proxy"] = "http://proxy.example.gov:80"

from boxy.cli import main  # noqa: E402

PREAMBLE = """\
# boxy Example Matrix: every engine x runtime x scheduler

18 end-to-end combinations (2 engines x 3 runtimes x 3 schedulers). Every
`### Running Command` below is REAL boxy output (generated by dry-run via
`hack/gen_matrix.py`, not hand-written; volume paths show as $PWD/... for the
generating machine, and pulled-model paths as the dry-run placeholder
/path/to/model). The E2E steps are identical for every combo:

```bash
boxy examples export ./examples          # drop the packaged profiles into ./examples first
boxy pull  --box examples/boxes/<box>.toml                          # skip for path-based models
boxy build --box examples/boxes/<box>.toml --location examples/locations/<loc>.toml   # apptainer only (OCI->SIF)
boxy serve --box examples/boxes/<box>.toml --location examples/locations/<loc>.toml
curl -s http://<host>:<port>/v1/models                              # readiness
curl -s http://<host>:<port>/v1/chat/completions -H 'Content-Type: application/json' \\
     -d '{"messages":[{"role":"user","content":"hello"}],"max_tokens":32}'
boxy bench --box examples/boxes/<box>.toml --batch-sizes 1,2,4,8 -o results.csv
boxy list && boxy stop --box examples/boxes/<box>.toml              # podman/docker lifecycle
```

Or skip the profiles entirely — the v2 front door resolves all of this from
the model alone (see README): `boxy serve <model> [--scheduler slurm --gpus N]`.

Engine notes: the llama.cpp box (`qwen-gguf`, port 8090) pulls a small GGUF
and runs on CPU anywhere (on ROCm/Intel GPU locations it auto-selects the
GPU-capable quay.io/ramalama images); the vLLM box (`vllm`, port 8000)
expects staged weights in `${MODELS_DIR}` and GPUs (cluster-class).
Scheduler notes: slurm/flux commands run from a login node; inside an
existing allocation use a location with `scheduler = "none"`. Apptainer
serve is foreground: stop with Ctrl-C or `scancel`/`flux cancel`.
"""

# (runtime, scheduler, location file) in presentation order
COMBOS = [
    ("podman", "none", "local-podman.toml"),
    ("docker", "none", "local-docker.toml"),
    ("apptainer", "none", "local-apptainer.toml"),
    ("podman", "slurm", "slurm-podman-cuda.toml"),
    ("apptainer", "slurm", "slurm-apptainer-cuda.toml"),
    ("docker", "slurm", "slurm-docker-cuda.toml"),
    ("podman", "flux", "flux-podman-rocm.toml"),
    ("apptainer", "flux", "flux-apptainer-rocm.toml"),
    ("docker", "flux", "flux-docker-rocm.toml"),
]
ENGINES = [("llama.cpp", "qwen-gguf.toml"), ("vllm", "vllm.toml")]


def dryrun(box: str, location: str) -> str:
    out = io.StringIO()
    with contextlib.redirect_stdout(out):
        rc = main(
            [
                "serve",
                "--box",
                str(EXAMPLES / "boxes" / box),
                "--location",
                str(EXAMPLES / "locations" / location),
                "--dryrun",
            ]
        )
    if rc != 0:
        raise SystemExit(f"dry-run failed for {box} x {location} (rc={rc})")
    return out.getvalue().replace(os.getcwd(), "$PWD").rstrip()


def generate() -> str:
    parts = [PREAMBLE]
    for engine, box in ENGINES:
        parts.append(f"\n## Engine: {engine} (box: `{box}`)\n")
        for runtime, scheduler, location in COMBOS:
            parts.append(f"### {engine} + {runtime} + {scheduler}  (`{location}`)\n")
            parts.append("```\n" + dryrun(box, location) + "\n```\n")
    return "\n".join(parts)


if __name__ == "__main__":
    os.chdir(ROOT)
    target = EXAMPLES / "MATRIX.md"
    target.write_text(generate())
    print(f"wrote {target}")
