"""boxy -> SkyPilot task YAML transpiler (SPEC §3c "CALL", roadmap Phase 5).

The cloud path delegates to SkyPilot instead of reimplementing provisioning:
a box + location becomes a `sky` task YAML, launched with `sky launch` (jobs)
or `sky serve up` (managed serving with SkyServe's readiness-gated replicas).
SkyPilot is never imported here — boxy stays serverless and air-gap-safe; the
YAML is plain text the user (or `boxy` later) hands to the `sky` CLI.
"""

from __future__ import annotations

import os
import shlex

from boxy import engines, envs
from boxy.box import Box
from boxy.location import Location

# Where the corporate trust bundle lands inside the task (file_mounts target).
CA_MOUNT = "/boxy/ca-bundle.crt"


def _yaml_str(value: str) -> str:
    if value == "" or any(c in value for c in ":#{}[]'\"|>&*!%@`"):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value


def _network_env(proxy: str | None, ca_bundle: str | None) -> dict[str, str]:
    """Corporate-network env for the task — EXPLICIT opt-in, unlike the on-net
    scheduler paths which auto-propagate (deploy._propagate_proxy): a corporate
    proxy is usually unreachable from a cloud VM, so injecting it blindly would
    break the VM's egress. `--proxy` says "this task runs on-net". Both cases
    emitted; the local no_proxy is preserved so intra-VM/localhost stays direct;
    the CA envs point at the file_mounts copy of the merged trust bundle."""
    env: dict[str, str] = {}
    if proxy:
        for var in ("HTTPS_PROXY", "https_proxy", "HTTP_PROXY", "http_proxy"):
            env[var] = proxy
        no = os.environ.get("NO_PROXY") or os.environ.get("no_proxy")
        if no:
            env["NO_PROXY"] = env["no_proxy"] = no
    if ca_bundle:
        env["SSL_CERT_FILE"] = env["REQUESTS_CA_BUNDLE"] = CA_MOUNT
    return env


def to_sky_task(
    box: Box,
    location: Location,
    port: int | None = None,
    extra_args: list[str] | None = None,
    serve: bool = False,
    proxy: str | None = None,
    ca_bundle: str | None = None,
) -> str:
    if not box.image:
        # an empty image emits `image_id: docker:` — invalid YAML that sky rejects
        # (finding 41; re-caught by the first real `sky.Task.from_yaml` validation).
        # Callers resolve engine+accelerator defaults first (deploy._apply_defaults).
        raise ValueError(f"box {box.name!r} has no image — resolve defaults before the sky "
                         "transpile (deploy._apply_defaults), or set [box] image explicitly")
    accelerator_type = getattr(location.resources, "accelerator_type", "")
    resolved_port = port or (box.ports[0] if box.ports else 8000)
    model_note = ""
    hf_flags: list[str] | None = None
    if box.model_is_transport_uri:
        # On the cloud path the engine downloads the model itself at task
        # start: hf://Org/Name becomes the bare repo id vLLM/HF understand.
        model_path = box.model.split("://", 1)[1]
        model_note = "# model is fetched by the engine at task start (cloud VM needs network)"
        if box.engine == "llama.cpp":
            # llama-server can't fetch a repo via -m; it has dedicated HF
            # download flags (sweep finding 43)
            parts = model_path.split("/")
            repo, filename = "/".join(parts[:2]), "/".join(parts[2:])
            hf_flags = ["--hf-repo", repo] + (["--hf-file", filename] if filename else [])
    else:
        model_path = box.model
    serve_cmd = engines.build_serve_cmd(box, location, model_path, port=resolved_port,
                                        extra_args=extra_args)
    if hf_flags is not None:
        # replace '-m <repo-path>' with the HF download flags
        m_index = serve_cmd.index("-m")
        serve_cmd[m_index:m_index + 2] = hf_flags
    if serve_cmd and serve_cmd[0] == "":
        # Sky's `run:` executes in a shell, not via the image ENTRYPOINT, so
        # the deferred-entrypoint sentinel needs a concrete binary here.
        # Layout differs per image family (sweep finding 42).
        from boxy import ramalama_shim

        serve_cmd[0] = (ramalama_shim.default_entrypoint(box.engine, box.image)
                        or "/app/llama-server")  # ghcr llama.cpp keeps it off $PATH
    run_cmd = shlex.join(serve_cmd)
    env = envs.build_env(box.env, location.accelerator or "none", location.offline, engine=box.engine)
    env = {**env, **_network_env(proxy, ca_bundle)}

    lines: list[str] = [
        "# Generated by boxy (box -> SkyPilot task). Launch with:",
        f"#   sky launch {'-c ' + box.name + ' ' if not serve else ''}<this-file>",
    ]
    if serve:
        lines.append("#   sky serve up <this-file>  # managed serving via SkyServe")
    lines += [
        f"name: {_yaml_str(box.name)}",
        "",
        f"num_nodes: {location.resources.nodes}",
        "",
        "resources:",
        f"  image_id: docker:{box.image}",
        f"  ports: [{resolved_port}]",
    ]
    if accelerator_type and location.resources.gpus_per_node:
        lines.append(f"  accelerators: {accelerator_type}:{location.resources.gpus_per_node}")
    if env:
        lines += ["", "envs:"]
        lines += [f"  {k}: {_yaml_str(v)}" for k, v in env.items()]
    if ca_bundle:
        # ship the merged corporate trust bundle onto the task; SSL_CERT_FILE /
        # REQUESTS_CA_BUNDLE in envs (above) already point at CA_MOUNT.
        lines += ["", "file_mounts:", f"  {CA_MOUNT}: {_yaml_str(ca_bundle)}"]
    lines += [
        "",
        "run: |",
    ]
    if model_note:
        lines.append(f"  {model_note}")
    lines.append(f"  {run_cmd}")
    if serve:
        lines += [
            "",
            "service:",
            "  readiness_probe:",
            "    path: /v1/models",
            "  replicas: 1",
        ]
    return "\n".join(lines) + "\n"
