"""boxy -> SkyPilot task YAML transpiler (SPEC §3c "CALL", roadmap Phase 5).

The cloud path delegates to SkyPilot instead of reimplementing provisioning:
a box + location becomes a `sky` task YAML, launched with `sky launch` (jobs)
or `sky serve up` (managed serving with SkyServe's readiness-gated replicas).
SkyPilot is never imported here — boxy stays serverless and air-gap-safe; the
YAML is plain text the user (or `boxy` later) hands to the `sky` CLI.
"""

from __future__ import annotations

import shlex

from boxy import engines, envs
from boxy.box import Box
from boxy.location import Location


def _yaml_str(value: str) -> str:
    if value == "" or any(c in value for c in ":#{}[]'\"|>&*!%@`"):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return value


def to_sky_task(
    box: Box,
    location: Location,
    port: int | None = None,
    extra_args: list[str] | None = None,
    serve: bool = False,
) -> str:
    accelerator_type = getattr(location.resources, "accelerator_type", "")
    resolved_port = port or (box.ports[0] if box.ports else 8000)
    model_note = ""
    if box.model_is_transport_uri:
        # On the cloud path the engine downloads the model itself at task
        # start: hf://Org/Name becomes the bare repo id vLLM/HF understand.
        model_path = box.model.split("://", 1)[1]
        model_note = "# model is fetched by the engine at task start (cloud VM needs network)"
    else:
        model_path = box.model
    run_cmd = shlex.join(engines.build_serve_cmd(box, location, model_path, port=resolved_port,
                                                 extra_args=extra_args))
    env = envs.build_env(box.env, location.accelerator or "none", location.offline, engine=box.engine)

    lines: list[str] = [
        "# Generated by boxy (box -> SkyPilot task). Launch with:",
        f"#   sky launch {'-c ' + box.name + ' ' if not serve else ''}<this-file>",
    ]
    if serve:
        lines.append(f"#   sky serve up <this-file>  # managed serving via SkyServe")
    lines += [
        f"name: {_yaml_str(box.name)}",
        "",
        f"num_nodes: {location.resources.nodes}",
        "",
        "resources:",
        f"  image_id: docker:{box.image}",
        f"  ports: [{resolved_port}]",
    ]
    if accelerator_type and location.resources.gpus_per_node:
        lines.append(f"  accelerators: {accelerator_type}:{location.resources.gpus_per_node}")
    if env:
        lines += ["", "envs:"]
        lines += [f"  {k}: {_yaml_str(v)}" for k, v in env.items()]
    lines += [
        "",
        "run: |",
    ]
    if model_note:
        lines.append(f"  {model_note}")
    lines.append(f"  {run_cmd}")
    if serve:
        lines += [
            "",
            "service:",
            "  readiness_probe:",
            "    path: /v1/models",
            "  replicas: 1",
        ]
    return "\n".join(lines) + "\n"
